name: 'Publish - npm'
on:
  pull_request:
    types: [ closed ]

jobs:
  publish:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/publish-npm.yml@c7819e687807cc6c2fe277ad11e4d7e15155fd33
    secrets: inherit
