name: 'Increment Version - npm'
on:
  pull_request:
    types: [ labeled, unlabeled, opened, reopened, synchronize ]

jobs:
  version:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/semver-check-increment-npm.yml@6c978f8ec0c92de1468a4a567e7fae1c6cf002c0
