name: 'Bump Version - npm'
on:
  pull_request:
    types: [ labeled, unlabeled, opened, reopened, synchronize ]

jobs:
  version:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/version-npm.yml@v1
